import { defineStore } from 'pinia'
import axios from 'axios'

const API_URL = 'http://localhost:5000/api/sheet'

export const dowerMapping = {
  con: ['agil', 'end', 'strg', 'rap', 'ref', 'spd'],
  int: ['clev', 'conc', 'ing', 'wisd', 'tem', 'will'],
  per: ['emp', 'seek', 'dizz', 'sigh'],
  car: ['pret', 'man', 'sec', 'ac'],
  hab: ['art', 'des'],
}

export const useSheetDataStore = defineStore('sheetData', {
  state: () => ({
    sheetData: {
      atr: {
        level: 1,
        xpInsert: 0,
        xpReach: 0,
        atrPoints: 0.3,
        devInsert: 0,
        devotion: 0,
        attributes: {
          con: 0,
          int: 0,
          per: 0,
          car: 0,
          hab: 0,
          psi: 0,
          esp: 0,
        },
        dower: {
          agil: 0,
          end: 0,
          strg: 0,
          rap: 0,
          ref: 0,
          spd: 0,
          clev: 0,
          conc: 0,
          ing: 0,
          wisd: 0,
          tem: 0,
          will: 0,
          emp: 0,
          seek: 0,
          dizz: 0,
          sigh: 0,
          pret: 0,
          man: 0,
          sec: 0,
          ac: 0,
          art: 0,
          des: 0,
        },
        wounds: [{ id: 1, name: '', stadium: 0, grade: 1, type: '' }],
        deityName: '',
        dp: 0,
        luckSelect: '',
        luck: 0,
        capCon: 0,
        plusCon: 0,
        capInt: 0,
        plusInt: 0,
        capPer: 0,
        plusPer: 0,
        capCar: 0,
        plusCar: 0,
        capHab: 0,
        plusHab: 0,
        capPsi: 0,
        plusPsi: 0,
        capEsp: 0,
        plusEsp: 0,
        plusReg: 0,
        regSelect: '',
        karmaGood: 0,
        karmaEvil: 0,
      },
      std: {
        name: '',
        race: '',
        mutation: '',
        temper: 'Temper',
        attitude: 'Attitude',
        faction: 'Faction',
        function: 'Function',
        age: 1,
        title: '',
        incarnation: 'Incarnation',
        constelation: 'Constelation',
        class1: '',
        class1Talent: 0,
        class2: '',
        class2Talent: 0,
        class3: '',
        class3Talent: 0,
        synergy: '',
        // Power section
        mistyc: 'Mistyc',
        acMistyc: 5,
        mxMistyc: 5,
        insiders: 'Insiders',
        acInsiders: 5,
        mxInsiders: 5,
        naturals: 'Naturals',
        acNaturals: 5,
        mxNaturals: 5,
        // Stats
        acHP: 5,
        mxHP: 5,
        acCP: 10,
        mxCP: 10,
        na: 1,
        arm: 0,
        acP: 0,
        mxP: 50,
        acRes: 5,
        mxRes: 5,
        acHam: 100,
        mxHam: 100,
        // Corruption and Madness
        percentCor: 0,
        minusCor: 10,
        percentLoc: 0,
        minusLoc: 5,
      },
      equip: {
        // Face
        face_name: '',
        face_t: '',
        face_c: 0,
        face_r: 0,
        face_e: '',
        face_u: 0,

        // Collar
        collar_name: '',
        collar_t: '',
        collar_c: 0,
        collar_r: 0,
        collar_e: '',
        collar_u: 0,

        // Tatoo
        tatoo_name: '',
        tatoo_t: '',
        tatoo_c: 0,
        tatoo_r: 0,
        tatoo_e: '',
        tatoo_u: 0,

        // Kenwa
        kenwa_name: '',
        kenwa_t: '',
        kenwa_c: 0,
        kenwa_r: 0,
        kenwa_e: '',
        kenwa_u: 0,

        // Bracelets
        leftBracelet_name: '',
        leftBracelet_t: '',
        leftBracelet_c: 0,
        leftBracelet_r: 0,
        leftBracelet_e: '',
        leftBracelet_u: 0,
        rightBracelet_name: '',
        rightBracelet_t: '',
        rightBracelet_c: 0,
        rightBracelet_r: 0,
        rightBracelet_e: '',
        rightBracelet_u: 0,

        // Rings
        leftRing_name: '',
        leftRing_t: '',
        leftRing_c: 0,
        leftRing_r: 0,
        leftRing_e: '',
        leftRing_u: 0,
        rightRing_name: '',
        rightRing_t: '',
        rightRing_c: 0,
        rightRing_r: 0,
        rightRing_e: '',
        rightRing_u: 0,

        // Piercings
        leftPir_name: '',
        leftPir_t: '',
        leftPir_c: 0,
        leftPir_r: 0,
        leftPir_e: '',
        leftPir_u: 0,
        rightPir_name: '',
        rightPir_t: '',
        rightPir_c: 0,
        rightPir_r: 0,
        rightPir_e: '',
        rightPir_u: 0,

        // Armor pieces
        head_name: '',
        head_t: '',
        head_a: 0,
        head_p: 0,
        head_m: '',
        head_c: 0,
        head_r: 0,
        head_e: '',
        head_d: 0,

        chest_name: '',
        chest_t: '',
        chest_a: 0,
        chest_p: 0,
        chest_m: '',
        chest_c: 0,
        chest_r: 0,
        chest_e: '',
        chest_d: 0,

        waist_name: '',
        waist_t: '',
        waist_a: 0,
        waist_p: 0,
        waist_m: '',
        waist_c: 0,
        waist_r: 0,
        waist_e: '',
        waist_d: 0,

        // Left side armor
        leftShoulder_name: '',
        leftShoulder_t: '',
        leftShoulder_a: 0,
        leftShoulder_p: 0,
        leftShoulder_m: '',
        leftShoulder_c: 0,
        leftShoulder_r: 0,
        leftShoulder_e: '',
        leftShoulder_d: 0,

        leftArm_name: '',
        leftArm_t: '',
        leftArm_a: 0,
        leftArm_p: 0,
        leftArm_m: '',
        leftArm_c: 0,
        leftArm_r: 0,
        leftArm_e: '',
        leftArm_d: 0,

        leftHand_name: '',
        leftHand_t: '',
        leftHand_a: 0,
        leftHand_p: 0,
        leftHand_m: '',
        leftHand_c: 0,
        leftHand_r: 0,
        leftHand_e: '',
        leftHand_d: 0,

        leftLeg_name: '',
        leftLeg_t: '',
        leftLeg_a: 0,
        leftLeg_p: 0,
        leftLeg_m: '',
        leftLeg_c: 0,
        leftLeg_r: 0,
        leftLeg_e: '',
        leftLeg_d: 0,

        leftFoot_name: '',
        leftFoot_t: '',
        leftFoot_a: 0,
        leftFoot_p: 0,
        leftFoot_m: '',
        leftFoot_c: 0,
        leftFoot_r: 0,
        leftFoot_e: '',
        leftFoot_d: 0,

        // Right side armor
        rightShoulder_name: '',
        rightShoulder_t: '',
        rightShoulder_a: 0,
        rightShoulder_p: 0,
        rightShoulder_m: '',
        rightShoulder_c: 0,
        rightShoulder_r: 0,
        rightShoulder_e: '',
        rightShoulder_d: 0,

        rightArm_name: '',
        rightArm_t: '',
        rightArm_a: 0,
        rightArm_p: 0,
        rightArm_m: '',
        rightArm_c: 0,
        rightArm_r: 0,
        rightArm_e: '',
        rightArm_d: 0,

        rightHand_name: '',
        rightHand_t: '',
        rightHand_a: 0,
        rightHand_p: 0,
        rightHand_m: '',
        rightHand_c: 0,
        rightHand_r: 0,
        rightHand_e: '',
        rightHand_d: 0,

        rightLeg_name: '',
        rightLeg_t: '',
        rightLeg_a: 0,
        rightLeg_p: 0,
        rightLeg_m: '',
        rightLeg_c: 0,
        rightLeg_r: 0,
        rightLeg_e: '',
        rightLeg_d: 0,

        rightFoot_name: '',
        rightFoot_t: '',
        rightFoot_a: 0,
        rightFoot_p: 0,
        rightFoot_m: '',
        rightFoot_c: 0,
        rightFoot_r: 0,
        rightFoot_e: '',
        rightFoot_d: 0,

        // Weapons and accessories
        weapon_name: '',
        weapon_t: '',
        weapon_a: 0,
        weapon_p: 0,
        weapon_m: '',
        weapon_c: 0,
        weapon_r: 0,
        weapon_e: '',
        weapon_dmg: 'D',

        shield_name: '',
        shield_t: '',
        shield_a: 0,
        shield_p: 0,
        shield_m: '',
        shield_c: 0,
        shield_r: 0,
        shield_e: '',
        shield_d: 0,

        sheath_name: '',
        sheath_t: '',
        sheath_a: 0,
        sheath_p: 0,
        sheath_m: '',
        sheath_c: 0,
        sheath_r: 0,
        sheath_e: '',
        sheath_d: 0,

        magic_name: '',
        magic_t: '',
        magic_a: 0,
        magic_p: 0,
        magic_m: '',
        magic_c: 0,
        magic_r: 0,
        magic_e: '',
        magic_dmg: 'D',

        range_name: '',
        range_t: '',
        range_a: 0,
        range_p: 0,
        range_m: '',
        range_c: 0,
        range_r: 0,
        range_e: '',
        range_dmg: 'D',

        // Quiver
        quiver_e: '',
        quiver_mx: '',
        quiver_text1: '',
        quiver_ac1: 0,
        quiver_text2: '',
        quiver_ac2: 0,
        quiver_text3: '',
        quiver_ac3: 0,
        quiver_text4: '',
        quiver_ac4: 0,
        quiver_text5: '',
        quiver_ac5: 0,
        quiver_text6: '',
        quiver_ac6: 0,
      },
      inv: {
        // Monedero
        cb: 0,
        pt: 0,
        or: 0,
        pl: 0,
        coin1: '',
        coin1Cant: 0,
        coin2: '',
        coin2Cant: 0,
        coin3: '',
        coin3Cant: 0,

        // Bolsa 1
        bag1: {
          name: 'Main',
          type: 'Bag',
          maxCapacity: 5,
          material: '',
          quality: 0,
          rarity: 0,
          effect: '',
          durability: 0,
          items: [
            {
              name: '',
              units: 0,
              durability: 0,
              effect: '',
              quality: 0,
              rarity: 0,
              type: '',
              price: 0,
              armor: 0,
              material: '',
              damage: '',
            },
          ],
        },

        // Bolsa 2
        bag2: {
          name: 'new',
          type: 'bag',
          maxCapacity: 0,
          material: '',
          quality: 0,
          rarity: 0,
          effect: '',
          durability: 0,
          items: [
            {
              name: '',
              units: 0,
              durability: 0,
              effect: '',
              quality: 0,
              rarity: 0,
              type: '',
              price: 0,
              armor: 0,
              material: '',
              damage: '',
            },
          ],
        },
      },
      dtPoints: {
        con: 0,
        int: 0,
        per: 0,
        car: 0,
        hab: 0,
      },
    },
  }),

  actions: {
    async loadSheet(name) {
      try {
        const res = await axios.get(`${API_URL}/load?name=${encodeURIComponent(name)}`)
        this.sheetData = res.data
      } catch (error) {
        console.error('Failed loading data from server:', error)
      }
    },

    async saveSheet(name) {
      try {
        await axios.post(API_URL + '/save', {
          sheetData: this.sheetData,
          name: name,
        })
      } catch (error) {
        console.error('Failed saving sheet in server:', error)
      }
    },
  },
})
